select p.PRODUCT_ID, p.PRODUCT_NAME, sum(o.AMOUNT*p.PRICE) TOTAL_SALES
from FOOD_PRODUCT p join FOOD_ORDER o
on p.PRODUCT_ID = o.PRODUCT_ID
where month(o.PRODUCE_DATE) = 5
group by p.PRODUCT_NAME
order by TOTAL_SALES desc, p.PRODUCT_ID;